[package]
name = "factory"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
hal = { path = "../hal" }
#esp-idf-sys = { version = "0.36.1", features = ["binstart"] }
esp-idf-hal = "0.45.2"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
