[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
#linker = "ldproxy"
linker = "xtensa-esp32s3-elf-gcc"
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,-Tlinkall.x",
]


[unstable]
build-std = ["core", "alloc"]

[env]
MCU="esp32s3"
SSID="ERROR 404"
PASSWORD="T0PZ3R44"

